name: Add Conferences to the Project Tracker with Labels and close
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    runs-on: ubuntu-latest
      
    steps:
      - name: close-issue
        if: ${{ github.event.label.name == 'conference' }}
        run: gh issue comment $ISSUE --body "Thank you for adding this event! \n We'll happily consider it for the next episode. \n\n The Issue autocloses but we'll be reviewing it at https://github.com/users/kjaymiller/projects/4/views/3" && gh issue close $ISSUE
        env:
         ISSUE: ${{ github.event.issue.html_url }}
         GH_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}